// <auto-generated />
namespace AppliedSystems.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedusertables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedusertables));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101932108_Added user tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
